receivers:
  otlp:
    protocols:
      grpc:

processors:
  tracepropagator:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tracepropagator]
      exporters: [logging]
