receivers:
  otlp:
    protocols:
      grpc:

processors:
  tracepropagator: {}

exporters:
  debug:
    verbosity: detailed
  otlphttp/grafana_cloud:
    endpoint: "https://otlp-gateway-prod-ap-south-1.grafana.net/otlp"
    auth:
      authenticator: basicauth/grafana_cloud

extensions:
  basicauth/grafana_cloud:
    client_auth:
      username: "${GRAFANA_USERNAME}"
      password: "${GRAFANA_PASSWORD}"

connectors:
  grafanacloud:
    host_identifiers: ["host.name"]


service:
  extensions:
    [
      basicauth/grafana_cloud
    ]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tracepropagator]
      exporters: [debug, otlphttp/grafana_cloud, grafanacloud]

    metrics/grafanacloud:
      receivers: [ grafanacloud ]
      exporters: [ otlphttp/grafana_cloud ]
