receivers:
  otlp:
    protocols:
      grpc:

processors:
  tracepropagator: {}

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tracepropagator]
      exporters: [debug]
