server {
    listen 4317;
    http2 on;
    location / {
        grpc_pass grpc://localhost:4317;
        grpc_set_header Host $host;
        grpc_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 4318;
    location / {
        proxy_pass http://localhost:4318;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
    }
}
